### ISSUE TITLE
Erro ao executar o jar criado pelo Spring Boot 

### ISSUE THREAD

**Issue by jjunio01** [ifpe-cti/saudegaranhuns#90]
@fabriciofx ao executar o jar esta sendo lançado o seguinte erro:
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-12-01 00:57:49.092 ERROR 288 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalArgumentException: Unable to create WebResourceSet from [C:\Users\Jose%20Junio\Documents\NetBeansProjects\saudegaranhuns\target\saudegaranhuns-1.0-SNAPSHOT.jar]
        at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:419) ~[tomcat-embed-core-8.5.20.jar!/:8.5.20]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.addMainJarResourceSet(JsfTomcatApplicationListener.java:166) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:145) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:38) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:101) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at br.edu.ifpe.garanhuns.sg.Aplicacao.main(Aplicacao.java:14) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [saudegaranhuns-1.0-SNAPSHOT.jar:na]

2017-12-01 00:57:49.108  INFO 288 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@14514713: startup date [Fri Dec 01 00:57:15 GMT-03:00 2017]; root of context hierarchy
2017-12-01 00:57:49.108  INFO 288 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

**Comment by fabriciofx** [comment]
@jjunio01 Favor formatar a saída do console aqui na issue.

**Comment by fabriciofx** [comment]
@jjunio01 Não consegui reproduzir o referido erro. Favor informar o passo a passo ou código que reproduza o erro apontado.

**Comment by jjunio01** [comment]
@fabriciofx Seguindo os passos abaixo:

1 - Depois de atualizar o branch local com o upstream/master

$ git fetch upstream
$git rebase upstream/master

2 - A aplicação é construída utilizando :
$ mvn clean package

3 - Executando a aplicação:
$ java -jar target/saudegaranhuns-1.0-SNAPSHOT.jar.

**Comment by fabriciofx** [comment]
@jjunio01 Fiz todos estes passos e ainda não consegui reproduzir o bug. Faça o seguinte: em uma pasta à parte, dê um clone no projeto e tente reproduzir o bug. Se ele aparecer, é alguma coisa na sua máquina.

**Comment by jjunio01** [comment]
@fabriciofx  FIz um clone em uma nova pasta e o bug se repetiu.

Estou tendo dificuldades em encontrar o que está ocasionando o erro.

Para executar o Spring Boot há alguma configuração e/ou arquivo a ser instalado na maquina local para que seja executado corretamente?

**Comment by fabriciofx** [comment]
@jjunio01 Não há configuração adicional. É só construir a aplicação e executá-la. Tente executar em modo debug para ter uma resposta mais detalhada:
````bash
$ java -jar target/saudegaranhuns-1.0-SNAPSHOT.jar --debug`
```

**Comment by jjunio01** [comment]
Já havia executado em modo debug, porém não consegui achar nada que me ajudasse.

**Comment by fabriciofx** [comment]
@jjunio01 Ainda continua do mesmo jeito? Se sim, experimente fazer o seguinte:

1. Apague o diretório `~/.m2` (este diretório é o cache de artefatos do maven)
2. Baixe o código direto do repositório `upstream`
3. Tente construir a aplicação e depois executá-la.

Se ainda tiver erro, comente aqui.

**Comment by jjunio01** [comment]
@fabriciofx  O Erro continua mesmo seguindo fazendo a nova tentativa.

**Comment by jjunio01** [comment]
@fabriciofx  Realizei duas tentativas seguindo os seguintes passos.

1 - Primeira tentativa.

 
Passo 1 - Apaguei a pasta .m2

Passo 2 - Fiz o Fetch do repositório upstream e o rebase com meu projeto master.

                $git fetch upstream
                $git rebase upstream/master

Passo 3 -  Construção da Aplicação.
                 $mvn clean package

Passo 4 - Executando o Spring Boot
               $ java -jar target/saudegaranhuns-1.0-SNAPSHOT.jar

2 Tentativa:

Passo 1 - Apagar a pasta  .m2

Passo 2 - Realizei o clone do repositório UPSTREAM

Passo 3 -  Construção da Aplicação.
                $mvn clean package

Passo 4 - Executando o Spring Boot
               $ java -jar target/saudegaranhuns-1.0-SNAPSHOT.jar


Mesmo depois das duas tentativas está com erro.

**Comment by jjunio01** [comment]
Erro lançado:

 :: Spring Boot ::        (v1.5.9.RELEASE)

2017-12-03 20:19:13.737  INFO 9952 --- [           main] br.edu.ifpe.garanhuns.sg.Aplicacao       : Starting Aplicacao on Junio with PID 9952 (C:\Users\Jose Junio\Documents\NetBeansProjects\teste\saudegaranhunsteste\target\saudegaranhuns-1.0-SNAPSHOT.jar started by Jose Junio in C:\Users\Jose Junio\Documents\NetBeansProjects\teste\saudegaranhunsteste)
2017-12-03 20:19:13.737  INFO 9952 --- [           main] br.edu.ifpe.garanhuns.sg.Aplicacao       : No active profile set, falling back to default profiles: default
2017-12-03 20:19:13.878  INFO 9952 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@14514713: startup date [Sun Dec 03 20:19:13 GMT-03:00 2017]; root of context hierarchy
2017-12-03 20:19:16.263  INFO 9952 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-12-03 20:19:16.419  INFO 9952 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.joinfaces.javaxfaces.ProjectStageAutoConfiguration' of type [org.joinfaces.javaxfaces.ProjectStageAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-12-03 20:19:17.466  INFO 9952 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-12-03 20:19:17.481  INFO 9952 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-12-03 20:19:17.497  INFO 9952 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.20
2017-12-03 20:19:21.452  INFO 9952 --- [ost-startStop-1] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2017-12-03 20:19:21.906  INFO 9952 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-12-03 20:19:21.906  INFO 9952 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 8028 ms
2017-12-03 20:19:24.859  INFO 9952 --- [ost-startStop-1] org.reflections.Reflections              : Reflections took 2047 ms to scan 6 urls, producing 728 keys and 3837 values
2017-12-03 20:19:25.812  INFO 9952 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-12-03 20:19:25.828  INFO 9952 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-12-03 20:19:25.828  INFO 9952 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-12-03 20:19:25.828  INFO 9952 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-12-03 20:19:25.828  INFO 9952 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-12-03 20:19:26.062  INFO 9952 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Inicializando Mojarra 2.2.14 ( 20161114-2152 unable to get svn info) para o contexto ''
2017-12-03 20:19:35.625  INFO 9952 --- [ost-startStop-1] j.e.r.webcontainer.jsf.application       : JSF1048: Anotações PostConstruct/PreDestroy presentes.  Os métodos ManagedBeans marcados com essas anotações informarão as anotações processadas.
2017-12-03 20:19:46.162  INFO 9952 --- [ost-startStop-1] .w.PostConstructApplicationEventListener : Running on PrimeFaces 6.1
2017-12-03 20:19:46.162  INFO 9952 --- [ost-startStop-1] .a.PostConstructApplicationEventListener : Running on PrimeFaces Extensions 6.1
2017-12-03 20:19:46.162  INFO 9952 --- [ost-startStop-1] o.omnifaces.VersionLoggerEventListener   : Using OmniFaces version 1.14
2017-12-03 20:19:46.897  INFO 9952 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@14514713: startup date [Sun Dec 03 20:19:13 GMT-03:00 2017]; root of context hierarchy
2017-12-03 20:19:47.131  INFO 9952 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-12-03 20:19:47.131  INFO 9952 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-12-03 20:19:47.209  INFO 9952 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-12-03 20:19:47.209  INFO 9952 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-12-03 20:19:47.287  INFO 9952 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-12-03 20:19:47.334  INFO 9952 --- [           main] oConfiguration$WelcomePageHandlerMapping : Adding welcome page: ServletContext resource [/index.html]
2017-12-03 20:19:47.709  INFO 9952 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-12-03 20:19:47.865  INFO 9952 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-12-03 20:19:47.881  INFO 9952 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-12-03 20:19:47.897 ERROR 9952 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalArgumentException: Unable to create WebResourceSet from [C:\Users\Jose%20Junio\Documents\NetBeansProjects\teste\saudegaranhunsteste\target\saudegaranhuns-1.0-SNAPSHOT.jar]
        at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:419) ~[tomcat-embed-core-8.5.20.jar!/:8.5.20]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.addMainJarResourceSet(JsfTomcatApplicationListener.java:166) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:145) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.joinfaces.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:38) ~[jsf-spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:101) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at br.edu.ifpe.garanhuns.sg.Aplicacao.main(Aplicacao.java:14) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [saudegaranhuns-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [saudegaranhuns-1.0-SNAPSHOT.jar:na]

2017-12-03 20:19:47.912  INFO 9952 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@14514713: startup date [Sun Dec 03 20:19:13 GMT-03:00 2017]; root of context hierarchy
2017-12-03 20:19:47.912  INFO 9952 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by fabriciofx** [comment]
@jjunio01 Localizei o problema. Há um [bug](https://github.com/joinfaces/joinfaces/issues/310) no Joinfaces, que é o módulo que o Spring Boot utiliza para fazer o JSF funcionar. Segundo ele, não pode haver espaço em branco no diretório em que está se executando a aplicação. Assim, temos três soluções:

1. Você mudar o nome de seu usuário do sistema, retirando os espaços em branco;
2. Mover o jar da construção para uma pasta onde não há espaço em branco e executar a aplicação de lá;
3. Atualizar o Spring Boot/ Joinfaces.

Infelizmente a solução `3.` está fora de cogitação no momento, uma vez que o update é para bibliotecas que ainda estão em beta. Assim, veja se a solução `1.` ou `2.` funciona para você e dê um feedback. Caso resolva, comente aqui que resolveu e feche a issue.

**Comment by jjunio01** [comment]
@fabriciofx Irei tentar as soluções indicadas.

**Comment by jjunio01** [comment]
Já consegui mudar o nome do usuário do sistema, porem a pasta de usuário permanece com o nome antigo(Que contem espaço em branco) , não consigo alterar por o windows está lançando um erro.

A solução 2, acho que recai na 1, pois as pastas dentro do meu usuário irão carregar como caminho (\Jose Junio).

Alterando apenas o nome do usuário não resolveu o erro.

**Comment by fabriciofx** [comment]
@jjunio01 Para a solução `2.` obviamente não seria para copiar para uma posta dentro do seu HOME, já que ele contém espaço em branco, certo? Que tal criar uma pasta como `C:\saudegaranhuns`, copiar o jar para lá e tentar executar de lá?

Para a solução `1.`, se você tivesse dado uma pesquisada, iria encontrar várias possíveis soluções, como [aqui](https://www.ghacks.net/2011/03/28/how-to-change-a-windows-account-name-and-user-profile-folder-name/) e [aqui](https://superuser.com/questions/890812/how-to-rename-the-user-folder-in-windows-10).

**Comment by jjunio01** [comment]
@fabriciofx  O problema era mesmo o bug referente ao espaço em branco no diretório.

Criei outro usuário e funcionou sem problemas o Spring Boot.  

A alteração de nome do usuário atual ainda estou tentando resolver, mesmo com os links informados e outros que achei a respeito nada deu certo ainda.

Considero a issue encerrada.

Grato.

**Comment by fabriciofx** [comment]
Seria interessante documentar isto. Eu cuido disso.

**Comment by fabriciofx** [comment]
@jjunio01 Favor ver a [observação da documentação](https://github.com/ifpe-cti/saudegaranhuns#executando). Se você concorda com o texto, favor fechar esta issue.

**Comment by jjunio01** [comment]
De acordo.
